services:
  - type: web
    name: panaderia
    env: docker
    plan: free
    region: oregon

    dockerfilePath: ./Dockerfile
    dockerContext: .

    # Render inyecta el PORT din√°micamente 
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JAVA_OPTS
        value: "-Xmx512m -Xss512k"

    # Solo vuelve a construir si hay cambios reales
    autoDeploy: true
